package zdict

func init() {
	addAttr(1, "User-Name", TypeString)
	addAttr2(2, "User-Password", TypeString, false, EncUsr)
	addAttr(3, "CHAP-Password", TypeRaw)
	addAttr(4, "NAS-IP-Address", TypeIP4)
	addAttr(5, "NAS-Port", TypeInt)
	addAttr(6, "Service-Type", TypeInt)
	addAttr(7, "Framed-Protocol", TypeInt)
	addAttr(8, "Framed-IP-Address", TypeIP4)
	addAttr(9, "Framed-IP-Netmask", TypeIP4)
	addAttr(10, "Framed-Routing", TypeInt)
	addAttr(11, "Filter-Id", TypeString)
	addAttr(12, "Framed-MTU", TypeInt)
	addAttr(13, "Framed-Compression", TypeInt)
	addAttr(14, "Login-IP-Host", TypeIP4)
	addAttr(15, "Login-Service", TypeInt)
	addAttr(16, "Login-TCP-Port", TypeInt)

	addAttr(18, "Reply-Message", TypeString)
	addAttr(19, "Callback-Number", TypeString)
	addAttr(20, "Callback-Id", TypeString)

	addAttr(22, "Framed-Route", TypeString)
	addAttr(23, "Framed-IPX-Network", TypeIP4)
	addAttr(24, "State", TypeRaw)
	addAttr(25, "Class", TypeRaw)
	addAttr(26, "Vendor-Specific", TypeVSA)
	addAttr(27, "Session-Timeout", TypeInt)
	addAttr(28, "Idle-Timeout", TypeInt)
	addAttr(29, "Termination-Action", TypeInt)
	addAttr(30, "Called-Station-Id", TypeString)
	addAttr(31, "Calling-Station-Id", TypeString)
	addAttr(32, "NAS-Identifier", TypeString)
	addAttr(33, "Proxy-State", TypeRaw)
	addAttr(34, "Login-LAT-Service", TypeString)
	addAttr(35, "Login-LAT-Node", TypeString)
	addAttr(36, "Login-LAT-Group", TypeRaw)
	addAttr(37, "Framed-AppleTalk-Link", TypeInt)
	addAttr(38, "Framed-AppleTalk-Network", TypeInt)
	addAttr(39, "Framed-AppleTalk-Zone", TypeString)

	addAttr(60, "CHAP-Challenge", TypeRaw)
	addAttr(61, "NAS-Port-Type", TypeInt)
	addAttr(62, "Port-Limit", TypeInt)
	addAttr(63, "Login-LAT-Port", TypeString)
}
